# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1003
    min-spare-threads: 30
  port: 7002
  connection-timeout: 5000ms
  servlet:
    context-path: /
  compression:
       enabled: true
spring:
  # 环境 dev|test|pre|prod
  profiles:
    active: prod
# 加载日志配置文件
logging:
  config: classpath:logback-fg.xml

